fix yarn error
polydice/base pull request #1
Opened 2016-12-14 09:26 UTC by HexterCH

在安裝 opencc 的時候會出現 yarn error
Fix by @frozenfung .
@dlackty  Please review.

2016-12-14 10:49 UTC, dlackty requested changes

2016-12-14 10:49 UTC, dlackty commented on DockerFile
> +RUN apt-get update && apt-get install -y build-essential apt-transport-https cmake python doxygen git libpq-dev libxml2-dev graphicsmagick yarn libxslt1-dev --no-install-recommends && rm -rf /var/lib
這邊有裝 yarn 上面也在裝 yarn？另外 doxygen 是必須的嗎？

2016-12-15 03:41 UTC, frozenfung commented on DockerFile
> +RUN apt-get update && apt-get install -y build-essential apt-transport-https cmake python doxygen git libpq-dev libxml2-dev graphicsmagick yarn libxslt1-dev --no-install-recommends && rm -rf /var/lib
第一行只是在抓 pubkey~

2016-12-15 05:48 UTC, HexterCH commented on DockerFile
> +RUN apt-get update && apt-get install -y build-essential apt-transport-https cmake python doxygen git libpq-dev libxml2-dev graphicsmagick yarn libxslt1-dev --no-install-recommends && rm -rf /var/lib
@dlackty 如果不裝 `doxygen`, `cmake`, `python`，在 opencc `make install` 會爆..XDDD

2016-12-15 06:52 UTC, dlackty commented on DockerFile
> +RUN apt-get update && apt-get install -y build-essential apt-transport-https cmake python doxygen git libpq-dev libxml2-dev graphicsmagick yarn libxslt1-dev --no-install-recommends && rm -rf /var/lib
Got it.

doxygen 是用來產生文件用的，但是 production 環境下應該不用建立文件？可以看一下 opencc makefile 怎麼去關閉文件產生功能？

2016-12-15 06:53 UTC, HexterCH commented on DockerFile
> +RUN apt-get update && apt-get install -y build-essential apt-transport-https cmake python doxygen git libpq-dev libxml2-dev graphicsmagick yarn libxslt1-dev --no-install-recommends && rm -rf /var/lib
ok

2016-12-15 11:01 UTC, merged